### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by olly1240** [mortie/mauncher#2]
Hi, both the AUR package and compiling from sources does not compile

Error returned:
```
/usr/bin/ld: mauncher-win.o:(.bss+0x0): multiple definition of `mauncher_win_opts'; mauncher.o:(.bss+0x0): first defined here
/usr/bin/ld: mauncher-ipc.o:(.bss+0x0): multiple definition of `mauncher_win_opts'; mauncher.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status

```

**Comment by mortie** [comment]
Sorry, it was just a stupid typo on my part. It should be fixed in https://github.com/mortie/mauncher/commit/adc625191fd748dbfee7824f94858bce8a574e3b.

**Comment by olly1240** [comment]
Now it compiles flawlessly! Thank you!
